#script for raspberry settings
cp -f crontab_update.sh /home/pi/
cp -f del_rb_photos.sh /home/pi/
cp -f dhcpcd.conf /etc/
cp -f dnsmasq.conf /etc/
cp -f hostapd.conf /etc/hostapd/
cp -f hosts /etc/
cp -f hostname /etc/
cp -f photos.sh /home/pi/
cp -f wpa_supplicant.conf /etc/wpa_supplicant/
cp -f dropbox_rb_update.sh /home/pi/
cp -f dropbox_uploader1.sh /home/pi/
cp -f .dropbox_uploader /home/pi/